saibing/bingo

langserver/workspace_refs.go
This fixes a panic when looking up a definition of a symbol in a main
package.
This is missing tests, and likely doesn't understand the full scope of the problem. Suggestions strongly welcomed.
=> Return error when package not found

langserver/internal/source/signature_help.go, langserver/lsp_signature_test.go, langserver/signature.go
This PR fixes https://github.com/saibing/bingo/issues/41.
=> Do not return error when signatureHelp is called with non-callable

langserver/hover.go
This PR fixes https://github.com/saibing/bingo/issues/43.
=> Do not return error for unsupported types on hover

langserver/completion.go
From the `UltiSnips` doc:
> The '$0' tabstop is a special tabstop. It is always the last tabstop
> in the snippet no matter how many tabstops are defined.
Defining `$0` after the final paren allows the cursor to easily end up there after completing the rest of the tabstops.
=> Define final tabstop, after final function paren

langserver/completion.go
```go
// Before
findById(id int) // selected: id int
// After
findById(id) // selected: id
```
Instead of inserting the type information as well I think it's more convenient to just enter the parameter name. This has higher changes of no need to edit the inserted snippet text `id`  vs. definitely having to edit and remove the inserted snippet text `id int` as it's invalid code.
=> Removing type information from param snippets

langserver/completion.go
In #75 I broke the snippet rendering for functions with more than 1 argument.
Before (missing identifier for second placeholder):
`Sscan(${1:str}, ${2:})${0}`
After:
`Sscan(${1:str}, ${2:a})${0}`
PR fixes broken rendering by flipping the order of trimming and splitting on whitespaces.
=> Bugfix (completion): first trimming params, then splitting on whitespaces

langserver/config.go, langserver/fs.go, langserver/handler.go, langserver/internal/cache/view.go, main.go
- adds supports for `build tags`: https://github.com/saibing/bingo/issues/84
- this PR includes only CLI flag support for build tags. If this will be merged, I will make another changes that supports `InitializationOptions`.
=> Adds build tags support

langserver/internal/cache/view.go
What's Observed
===============
Bingo returns errors when I open files in the $GOPATH/pkg/mod directory
(on Emacs with lsp-mode).
For example, textDocument/hover requests fail with the following error
message:
```
--> request #165: textDocument/hover:
{"textDocument":{"uri":"file:///home/yudai/gopath/pkg/mod/k8s.io/kubernetes@v1.13.3/pkg/kubelet/pod/pod_manager.go"},"position":{"line":131,"character":0}}
<-- error #165: textDocument/hover: {"code":0,"message":"go [list -f
{{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go:
creating new go.mod: module k8s.io/kubernetes\ngo: copying requirements
from ../../../Godeps/Godeps.json\ngo: open
/home/yudai/gopath/pkg/mod/k8s.io/kubernetes@v1.13.3/go.mod: permission
denied\n","data":null}
```
Root Cause
==========
The command `go …
=> Fix errors in non-moduled dependencies

README.md
* move instructions to `README.md`. Just makes things much easier.
* update `vscode-go` `go.languageServerFlags` settings example.
**NB:** Flags seem to indicate that `--format-style=<style>` is supported whilst I could only get this to work
```json
...
"go.languageServerFlags": [
"-enhance-signature-help",
"-trace",
"-format-style=goimports",
],
...
```
=> Documentation: Move to README.md and update vscode-go settings

main.go
Since `GoimportsLocalPrefix` is already present in the bingo's config, we only need to create a flag and pass it to the config.
=> Add flag for goimports 'local' option

langserver/completion.go
This fixes a problem I had with emacs lsp-mode.
=> langserver: add check for client snippet completion capability

langserver/fs.go, langserver/handler.go
Currently, `build-tags` option is passed as build flags incorrectly, this PR will fix this.
=> make build-tags option passed correctly

langserver/config.go, langserver/initialization.go
- add BuildTags to InitializationOptions.
- remaining task of #86.
=> add BuildTags parameter to InitializationOptions

README.md, langserver/hover.go
We want `type error interface{Error() String}` to appear instead of `type builtin.error interface{Error() invalid type}`.
Not sure if I've broken anything, I'm going to test it further but a preliminary look would be good.
Fixes: https://github.com/saibing/bingo/issues/76
=> Fix Hover for BuiltIn Types

langserver/lsp_definition_test.go, langserver/lsp_xdefinition_test.go
`TestXDefinition/go_root/xdefinition-goroot-a.go:1:40`: fix test
```sh
$ go test ./...
...
--- FAIL: TestXDefinition (0.01s)
--- FAIL: TestXDefinition/go_root (0.00s)
--- FAIL: TestXDefinition/go_root/xdefinition-goroot-a.go:1:40 (0.00s)
lsp_xdefinition_test.go:100:
got  "/usr/local/go/src/fmt/print.go:274:6 id:fmt/-/Println name:Println package:fmt packageName:fmt recv: vendor:false"
want "/usr/local/go/src/fmt/print.go:263:6 id:fmt/-/Println name:Println package:fmt packageName:fmt recv: vendor:false"
...
```
It should be `/usr/local/go/src/fmt/print.go:274:6...`, proof:
```sh
$ grep -n 'Println' /usr/local/go/src/fmt/print.go
265:    p.doPrintln(a)
271:// Println formats using the default formats for its operands and writes to standard output.
274:func Println(a ...interface{}) (n int, …
```
=> Fix some failing tests

langserver/completion.go, langserver/hover.go, langserver/internal/source/completion.go, langserver/internal/source/hover.go
**WIP:** Needs more work and input. I don't expect this PR to be approved, I guess I am just asking for input on how to improve the implementation
---
**Changes:**
* Remove `LangHandler:getImportPackage` and call `goast.SearchImportPackage` directly.
* Move `LangHandler:findComments` from `langserver/hover.go` to `langserver/internal/source/hover.go` as `FindComments`.
* Refactor `FindComments` and introduce new function `PullComments`.
* Move `packageDoc` from `langserver/hover.go` to `langserver/internal/source/hover.go`.
* Move `joinCommentGroups` from `langserver/hover.go` to `langserver/internal/source/hover.go`.
https://microsoft.github.io/language-server-protocol/specification#textDocument_completion
---
**Screenshot:**
---
See: https://github.com/saibing/bingo/issues/91
=> textDocument/completion: set CompletionItem.Documentation

langserver/internal/refs/refs_test.go, langserver/lsp_completion_test.go, langserver/lsp_definition_test.go, langserver/lsp_document_symbol_test.go, langserver/lsp_formatting_test.go, langserver/lsp_hover_test.go, langserver/lsp_implementations_test.go, langserver/lsp_references_test.go, langserver/lsp_renaming_test.go, langserver/lsp_signature_test.go, langserver/lsp_test.go, langserver/lsp_type_definition_test.go, langserver/lsp_workspace_references_test.go, langserver/lsp_workspace_symbol_test.go, langserver/lsp_xdefinition_test.go, langserver/symbol_test.go
**Summary:** The lines below, in `TestCompletion`, are causing certain tests to fail and I cannot figure out why. A solution that I think will work is to remove the global server being shared across the tests then we won't have such issues.
```go
cache := h.project.Cache()
h.project.SetCache(nil)
defer h.project.SetCache(cache)
```
---
**Notes:**
1. Only failing test at the moment, which I cannot figure out why it's failing, is
```sh
$ gotest -count=1 ./...
?   	github.com/saibing/bingo	[no test files]
ok  	github.com/saibing/bingo/langserver	15.616s
?   	github.com/saibing/bingo/langserver/internal/cache	[no test files]
ok  	github.com/saibing/bingo/langserver/internal/diff	0.007s
?   	github.com/saibing/bingo/langserver/internal/goast	[no test files]
? …
```
=> Misc refactor

langserver/handler.go
Previously, each build tag was being passed to `go list` as a separate argument, which caused `go list` to interpret the second one as a package name, which it couldn't find. This meant that bingo only worked with zero or one build tags, not more than one.
Join the build tags with spaces and pass them all as a single argument to `go list`.
=> Fix handling of multiple build tags

langserver/format.go, langserver/position.go
There are two problems in code formatting:
1. According to currently `gopls`'s internal implementation, end point's offset  is always `-1`, which makes the `Offset()` panic.  Actually, as I tested in my neovim environment, checking file's ending is unnecessary now, so I removed these logic, and it works fine for me.
2. `internal/source`'s line and column number always starts from `1`, so we should correct it first. Otherwise code formatting cannot work properly.
@saibing PTAL
=> fixed bug in code formatting

.golangci.yml, Makefile
* add `.golangci.yml` config file.
* add `Makefile`.
* add `make devtools` and `make lint` rules.
---
```sh
$ make lint                                       
---> Linting ... 
golangci-lint run --config ./.golangci.yml ./...
langserver/internal/source/completion.go:495:3: ifElseChain: rewrite if-else to switch statement (gocritic)
langserver/internal/source/completion.go:540:9: ifElseChain: rewrite if-else to switch statement (gocritic)
langserver/internal/source/hover.go:79:2: ifElseChain: rewrite if-else to switch statement (gocritic)
langserver/ast.go:157:3: caseOrder: case *ast.CommClause must go before the ast.Stmt case (gocritic)
langserver/hover.go:126:2: ifElseChain: rewrite if-else to switch statement (gocritic)
langserver/lsp_definition_test.go:122:2: ifElseChain: rewrite …
```
=> Add golangci-lint (https://github.com/golangci/golangci-lint) linter:

langserver/handler_shared.go, langserver/hover.go, langserver/hover_test.go, langserver/lsp_hover_test.go, langserver/lsp_test.go
Format anonymous struct in `hoverIdent` in `langserver/hover.go`:
* Call `prettyPrintTypesString` with the result of `types.ObjectString(o, qf)`.
* If we are hovering over `*types.PkgName` call `go/types.ObjectString`
instead of `prettyPrintTypesString`.
* Misc formatting of code.
tests `langserver/lsp_hover_test.go` and `langserver/lsp_test.go`: call `t.Helper()`
* Call `t.Helper()` in the test helpers methods so that when tests fail
the actual place is printed instead of the helper method.
Issue: https://github.com/saibing/bingo/issues/143
=> Format anonymous struct issue 143
